barcode_proj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path,include
from .views import index,barcode
app_name="app"
urlpatterns = [
    path("",index,name="index"),
    path("barcode/<str:Product_name>/<int:pk>/",barcode,name="barcode"),


]

products/models.py
from django.db import models
import barcode
from barcode.writer import ImageWriter
from io import BytesIO
from django.core.files import File
# Create your models here.
class Products(models.Model):
    Product_name=models.CharField(max_length=200)
    barcode=models.ImageField(upload_to='images/',blank=True)
    country_id=models.CharField(max_length=1,null=True)
    manufacturer_id=models.CharField(max_length=6,null=True)
    number_id=models.CharField(max_length=5,null=True)
    


    def __str__(self):
        return str(self.Product_name)

    def save(self,*args,**kwargs):
        EAN=barcode.get_barcode_class('ean13')
        ean=EAN(f'{self.country_id}{self.manufacturer_id}{self.number_id}',writer=ImageWriter())
        buffer=BytesIO()
        ean.write(buffer)
        self.barcode.save(f'{self.Product_name}.png',File(buffer),save=False)
        return super().save(*args,**kwargs)

products/forms.py
from django import forms
from .models import Products
class ProductsForm(forms.ModelForm):
    class Meta:
        model=Products
        fields=['Product_name','country_id','manufacturer_id','number_id']    

products/views.py
from django.shortcuts import render,redirect

# Create your views here.
from .models import Products
from .forms import ProductsForm

def index(request):
    productform=ProductsForm()
    if request.method=='POST':
        form=ProductsForm(request.POST)
        if form.is_valid():
            post=form.save()
            print(post.pk,post.Product_name)
            
            return redirect(f'barcode/{post.Product_name}/{post.pk}')
    return render(request,'index.html',{'form':productform})


def barcode(request,Product_name,pk):
    pro=Products.objects.filter(Product_name=Product_name,pk=pk)

    return render(request,'barcode.html',{'pro':pro})

products/templates/barcode.html
{% extends "base.html" %}
{% load static %}
    {% block scripts %}
    {% endblock scripts %}
<!-- 
    {% for prod in products %}
      <h4>Product No.{{forloop.counter}} with number id:<a href="{% url 'app:barcode' prod.name prod.pk %}"> {{prod.number_id}}</a>
      </h4>
    {% endfor %} -->

    {% block css %}
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'products/style.css'%}">
    {% endblock css %}

   {% block content %}
    {% if pro %}
    {% for p in pro %}    

    <div class="wrapper">
        <h1 class="m-4">Barcode Generated</h1>

        <header>Product name: {{p.Product_name}}</header>
        <nav>
         <p> Country ID:
          {{p.country_id}}</p>
          <p>Manufacturer ID:{{p.manufacturer_id}}</p>
          <p>Number ID:{{p.number_id}}</p>

        </nav>
        

        <section>

    <img class="img-thumbnail" src="{{p.barcode.url}}" alt="">
    <br>
    <a href="/" class="btn btn-outline-info mt-4">Generate a new barcode</a>

        </section>
      </div>

    {% endfor %}
    {% else %}
    <h3>No barcode avalaible for the product you searched</h3>
    <br>
    <a href="/">Generate a barcode</a>

    {% endif %}
   {% endblock content %}

products/templates/index.html
{% extends "base.html" %}
{% load materializecss %}

{% block css %}
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css" integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
{% endblock css %}
{% block title %}
  form
{% endblock title %}
{% block content %}
<body style="text-align: center;background-color:rgb(82, 81, 81);color: white;">
<h2>Barcode Generator</h2>
<br>
<form method="POST">
    {% csrf_token %}

    {{form|materializecss}}
    <!-- <input type="submit" value="Submit" class="btn waves-effect waves-teal btn-large"> -->
    <button  class="btn waves-effect waves-teal btn-large" type="submit" name="action">Submit
        <i class="material-icons right">send</i>
      </button>
</form>
</body>

{% endblock content %}
    
{% block scripts %}
<script
src="https://code.jquery.com/jquery-3.3.1.min.js"
integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js" integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>

<script>
$(document).ready(function(){

// Initialize materialize data picker
$('.datepicker').datepicker({'format': 'yyyy-mm-dd'});
$('select').formSelect();

});
</script>

{% endblock scripts %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!--Custom css ADD HERE-->
    {% block css %}
      
    {% endblock css %}
    
    <title>Barcode Generator - {% block title %}{% endblock title %}</title>
  </head>
  <body>
    <div class="ui container">
      {% block content %}
      {% endblock content %}
    </div>

    {% block scripts %}
    {% endblock scripts %}
   
   <!--Custom js ADD HERE-->

  </body>
</html>